// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-09-02 12:25:13
// Dictionary type: task_type

package constants
// task_type - 计划任务相关
const (
	TaskTypeHttpCall = "http_call" // HttpCall
	TaskTypeFunction = "function" // Function
	TaskTypeScriptExec = "script_exec" // ScriptExec
)

// task_typeLabelMap label mapping for task_type
var task_typeLabelMap = map[string]string{
	TaskTypeHttpCall: "HttpCall",
	TaskTypeFunction: "Function",
	TaskTypeScriptExec: "ScriptExec",
}

// task_typeOptions all options for task_type
var task_typeOptions = []struct{
	Value string
	Label string
}{
	{ TaskTypeHttpCall, "HttpCall" },
	{ TaskTypeFunction, "Function" },
	{ TaskTypeScriptExec, "ScriptExec" },
}
