// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-08-19 18:49:54
// Dictionary type: task_type

package constants
// task_type - 计划任务相关
const (
	TaskTypeDatabaseJob = "database_job" // 数据库相关任务
	TaskTypeHttpCall = "http_call" // HTTP请求任务
	TaskTypeFunction = "function" // 函数任务
	TaskTypeFileProcess = "file_process" // 文件处理任务
	TaskTypeScriptExec = "script_exec" // 脚本执行任务
)

// task_typeLabelMap label mapping for task_type
var task_typeLabelMap = map[string]string{
	TaskTypeDatabaseJob: "数据库相关任务",
	TaskTypeHttpCall: "HTTP请求任务",
	TaskTypeFunction: "函数任务",
	TaskTypeFileProcess: "文件处理任务",
	TaskTypeScriptExec: "脚本执行任务",
}

// task_typeOptions all options for task_type
var task_typeOptions = []struct{
	Value string
	Label string
}{
	{ TaskTypeDatabaseJob, "数据库相关任务" },
	{ TaskTypeHttpCall, "HTTP请求任务" },
	{ TaskTypeFunction, "函数任务" },
	{ TaskTypeFileProcess, "文件处理任务" },
	{ TaskTypeScriptExec, "脚本执行任务" },
}
