// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-08-31 06:19:42
// Dictionary type: task_exec

package constants
// task_exec - 计划任务执行类型
const (
	TaskExecOnetime = "one_time" // OneTime
	TaskExecRecurring = "recurring" // Recurring
)

// task_execLabelMap label mapping for task_exec
var task_execLabelMap = map[string]string{
	TaskExecOnetime: "OneTime",
	TaskExecRecurring: "Recurring",
}

// task_execOptions all options for task_exec
var task_execOptions = []struct{
	Value string
	Label string
}{
	{ TaskExecOnetime, "OneTime" },
	{ TaskExecRecurring, "Recurring" },
}
