// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-08-21 23:00:17
// Dictionary type: task_type

package constants
// task_type - 计划任务相关
const (
	TaskTypeHttpCall = "http_call" // HTTP请求任务
	TaskTypeScriptExec = "script_exec" // 脚本执行任务
	TaskTypeFunction = "function" // 函数任务
)

// task_typeLabelMap label mapping for task_type
var task_typeLabelMap = map[string]string{
	TaskTypeHttpCall: "HTTP请求任务",
	TaskTypeScriptExec: "脚本执行任务",
	TaskTypeFunction: "函数任务",
}

// task_typeOptions all options for task_type
var task_typeOptions = []struct{
	Value string
	Label string
}{
	{ TaskTypeHttpCall, "HTTP请求任务" },
	{ TaskTypeScriptExec, "脚本执行任务" },
	{ TaskTypeFunction, "函数任务" },
}
