// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-08-17 20:07:00
// Dictionary type: api_group

package constants
// api_group - Api分组
const (
	ApiGroupAuth = "auth" // Auth
	ApiGroupOther = "other" // Other
)

// api_groupLabelMap label mapping for api_group
var api_groupLabelMap = map[string]string{
	ApiGroupAuth: "Auth",
	ApiGroupOther: "Other",
}

// api_groupOptions all options for api_group
var api_groupOptions = []struct{
	Value string
	Label string
}{
	{ ApiGroupAuth, "Auth" },
	{ ApiGroupOther, "Other" },
}
