// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-08-25 06:10:22
// Dictionary type: api_method

package constants
// api_method - api_method
const (
	ApiMethodOptions = "OPTIONS" // OPTIONS
	ApiMethodPut = "PUT" // PUT
	ApiMethodDelete = "DELETE" // DELETE
	ApiMethodPost = "POST" // POST
	ApiMethodGet = "GET" // GET
)

// api_methodLabelMap label mapping for api_method
var api_methodLabelMap = map[string]string{
	ApiMethodOptions: "OPTIONS",
	ApiMethodPut: "PUT",
	ApiMethodDelete: "DELETE",
	ApiMethodPost: "POST",
	ApiMethodGet: "GET",
}

// api_methodOptions all options for api_method
var api_methodOptions = []struct{
	Value string
	Label string
}{
	{ ApiMethodOptions, "OPTIONS" },
	{ ApiMethodPut, "PUT" },
	{ ApiMethodDelete, "DELETE" },
	{ ApiMethodPost, "POST" },
	{ ApiMethodGet, "GET" },
}
