// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-09-08 11:35:55
// Dictionary type: log_level

package constants
// log_level - 日志级别
const (
	LogLevelError = "error" // 错误
	LogLevelFatal = "fatal" // 致命
	LogLevelClose = "close" // 关闭
	LogLevelWarning = "warning" // 警告
	LogLevelInfo = "info" // 信息
	LogLevelDebug = "debug" // 调试
)

// log_levelLabelMap label mapping for log_level
var log_levelLabelMap = map[string]string{
	LogLevelError: "错误",
	LogLevelFatal: "致命",
	LogLevelClose: "关闭",
	LogLevelWarning: "警告",
	LogLevelInfo: "信息",
	LogLevelDebug: "调试",
}

// log_levelOptions all options for log_level
var log_levelOptions = []struct{
	Value string
	Label string
}{
	{ LogLevelError, "错误" },
	{ LogLevelFatal, "致命" },
	{ LogLevelClose, "关闭" },
	{ LogLevelWarning, "警告" },
	{ LogLevelInfo, "信息" },
	{ LogLevelDebug, "调试" },
}
