// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-08-11 21:43:11
// Dictionary type: file_storage_engine

package constants
// file_storage_engine - storage_engine
const (
	FileStorageEngineAliyunoss = "aliyunoss" // 阿里云oss
	FileStorageEngineLocal = "local" // 本地存储
)

// file_storage_engineLabelMap label mapping for file_storage_engine
var file_storage_engineLabelMap = map[string]string{
	FileStorageEngineAliyunoss: "阿里云oss",
	FileStorageEngineLocal: "本地存储",
}

// file_storage_engineOptions all options for file_storage_engine
var file_storage_engineOptions = []struct{
	Value string
	Label string
}{
	{ FileStorageEngineAliyunoss, "阿里云oss" },
	{ FileStorageEngineLocal, "本地存储" },
}
